---
title: "quality control"
author: "Yu"
date: "2023-10-13"
output: html_document
---

```{r}
library(Seurat)
library(tidyverse)
library(ggplot2)
library(patchwork)
library(clusterProfiler)
library(org.Mm.eg.db)
library(enrichplot)
library(rrvgo)
library(scRNAtoolVis)
library(ggSCvis)
```


```{r}
load("new.merge.obj.Rdata")
```

```{r}
cluster.n <- c(0,1,2,3,4,5)
anatomy <- c("Cortex","Thalamus","Hippocampus","OLF","Hypothalamus","Cerebral Nuclei")

cluster_anatomy.df <- data.frame(cluster = cluster.n,
                                 anatomy = anatomy)

merge.obj$anatomy <- cluster_anatomy.df$anatomy[match(merge.obj$seurat_clusters,cluster_anatomy.df$cluster)]

merge.obj$anatomy <- factor(merge.obj$anatomy, levels = c("Cortex","Thalamus","Hippocampus","OLF","Hypothalamus","Cerebral Nuclei"))

```

```{r}
DimPlot(merge.obj, group.by = "anatomy", label = T)
ggsave(paste("./Dimplot.anatomy.labeled.tiff", sep = ""), device='tiff', height = 1000, width = 1000, unit = 'px')

DimPlot(merge.obj, group.by = "anatomy", label = F, pt.size = 0.01) + 
  ggtitle("")+
  NoLegend()
ggsave(paste("./Fig_section2/Dimplot.anatomy.res300.unlabeled.tiff", sep = ""), device='tiff', 
       dpi = 300,height = 1500, width = 1500, unit = 'px')

clusterCornerAxes(object = merge.obj,reduction = 'umap',
                  noSplit = T,
                  addCircle = TRUE) + 
  ggtitle("")+
  NoLegend()
ggsave(paste("./Fig_section2/Dimplot.axis.tiff", sep = ""), device='tiff',dpi = 300, height = 1000, width = 1000, unit = 'px')

DimPlot(merge.obj, group.by = "anatomy", label = F, pt.size = 0.01) + NoLegend()
ggsave(paste("./Fig_section2/Dimplot.anatomy.unlabeled.tiff", sep = ""), device='tiff',dpi = 100, height = 1000, width = 1000, unit = 'px')

SpatialDimPlot(merge.obj, group.by = "anatomy",
               pt.size.factor = 1.6,
               ncol = 4, label = F)
ggsave(paste("./SpDimplot.anatomy.unlabeled.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialDimPlot(merge.obj, group.by = "anatomy",
               images = "d0_cc_1h_rep1",
               pt.size.factor = 1.6, label = F)
ggsave(paste("./Fig_section2/SpDimplot.demo.anatomy.unlabeled.tiff", sep = ""), device='tiff', dpi=500, height = 6, width = 6, unit = 'in')

SpatialDimPlot(merge.obj, group.by = "anatomy",
               images = "d0_cc_1h_rep1",
               pt.size.factor = 1.6, label = T)
ggsave(paste("./Fig_section2/SpDimplot.demo.anatomy.labeled.tiff", sep = ""), device='tiff', dpi=500, height = 6, width = 6, unit = 'in')
```


```{r}

for (pic in Images(merge.obj)){
  SpatialDimPlot(merge.obj, group.by = "anatomy",
               pt.size.factor = 1.6,
               images = pic, label = F)
  ggsave(paste("./Fig_section2/SpDimplot.anatomy.",pic,"unlabeled.tiff", sep = ""), device='tiff',dpi = 100,height = 1000, width = 1000, unit = 'px')
}

```




```{r}

sum(merge.obj$nFeature_Spatial > 200 & merge.obj$nCount_Spatial > 500)
ncol(merge.obj)
merge.obj <- subset(merge.obj, subset = nFeature_Spatial > 200 & nCount_Spatial > 500) # 45843 before filtering
```


```{r}

for (gene in c("Ovol2","Abhd12b","Thbs4","Ptpn14","Hcrt","Adora2a")) {
  SpatialFeaturePlot(merge.obj, features = gene,
                   images = "d0_cc_1h_rep1",
                   pt.size.factor = 1.6)
  ggsave(paste("./Fig_section2/SpatialFeaturePlot.",gene,".tiff", sep = ""), device='tiff', dpi = 100,height = 1000, width = 1000, unit = 'px')
}
```



```{r}
for (gene in c("B2m","Top1","Actb")){
  VlnPlot(merge.obj, features = gene, group.by = "sample", pt.size = 0, slot = "counts",cols = c(rep("#c3d9ef",14)))+NoLegend()
  ggsave(paste("./Fig_section2/Vnlot.housekeeping",gene,".tiff", sep = ""), device='tiff',dpi = 100, height = 1000, width = 1000, unit = 'px')
  ggsave(paste("./Fig_section2/Vnlot.res300.housekeeping",gene,".tiff", sep = ""), device='tiff',
         dpi = 300, height = 2000, width = 2000, unit = 'px')
  VlnPlot(merge.obj, features = gene, group.by = "sample", pt.size = 0,slot = "data",cols = c(rep("#c3d9ef",14)))+NoLegend()
  ggsave(paste("./Fig_section2/Vnlot.housekeeping.normalized",gene,".tiff", sep = ""), device='tiff',
         dpi = 100, height = 1000, width = 1000, unit = 'px')
  ggsave(paste("./Fig_section2/Vnlot.res300.housekeeping.normalized",gene,".tiff", sep = ""), device='tiff',
         dpi = 300, height = 2000, width = 2000, unit = 'px')
}

```


```{r}
Idents(merge.obj) <- merge.obj$anatomy
merge.obj <- FindSubCluster(merge.obj, resolution = 0.8,
                            cluster = "Neocortex",subcluster.name = "Neocortex.sub",graph.name = "Spatial_snn")
SpatialFeaturePlot(merge.obj, features = "Lypd1",
                   images = "d0_cc_1h_rep1",
                   pt.size.factor = 1.6)
SpatialDimPlot(merge.obj, group.by = "Neocortex.sub",
               images = "d0_cc_1h_rep1",
               pt.size.factor = 1.6, label = F)
```


```{r}
merge.obj$sample <- merge.obj$orig.ident

merge.obj$sample <- factor(merge.obj$sample, levels = unique(merge.obj$orig.ident))
```



```{r}
VlnPlot(merge.obj, features = "nCount_Spatial", group.by = "sample", pt.size = 0, cols = c(rep("#c3d9ef",14))) +
  geom_hline(yintercept = 500)+
  scale_y_continuous(breaks = c(500,20000,40000, 60000),limits = c(0, 60000)) +
  ggtitle("")+
  NoLegend()

ggsave(paste("./Fig_section2/Vnlot.nCount.tiff", sep = ""), device='tiff', dpi=100, height = 1000, width = 1000, unit = 'px')
ggsave(paste("./Fig_section2/Vnlot.res300.nCount.tiff", sep = ""), device='tiff', dpi=300, height = 2000, width = 2000, unit = 'px')

VlnPlot(merge.obj, features = "nFeature_Spatial", group.by = "sample", pt.size = 0, cols = c(rep("#c3d9ef",14)))+
  geom_hline(yintercept = 200,linetype="dashed")+
  scale_y_continuous(breaks = c(200,3000,6000,9000)) +
  ggtitle("")+
  NoLegend()
ggsave(paste("./Fig_section2/Vnlot.nFeature.tiff", sep = ""), device='tiff', dpi=100, height = 1000, width = 1000, unit = 'px')
ggsave(paste("./Fig_section2/Vnlot.res300.nFeature.tiff", sep = ""), device='tiff', dpi=300, height = 2000, width = 2000, unit = 'px')
```

```{r}
anatomy.marker <- FindAllMarkers(merge.obj, only.pos = T,
                                 pseudocount.use = 0.001)
```



```{r}
top_10markers <- anatomy.marker %>% group_by(cluster)  %>% top_n(20, avg_log2FC)

write.csv(top_10markers, file = "./Fig_section2/top20.regional.marker.csv")

top_10.markers <- anatomy.marker %>% group_by(cluster)  %>% top_n(10, avg_log2FC)
```

```{r}
DoHeatmap(merge.obj,group.by = "anatomy", features = unique(top_10markers$gene))

DoHeatmap(merge.obj, group.by = "anatomy",features = unique(top_10markers$gene))+
  scale_fill_gradientn(colors = c("#0099CC", "white", "#CC0033"))+ NoLegend()
ggsave(paste("./Fig_section2/Dohtmp.300dpi.region.marker.tiff", sep = ""), device='tiff',  height = 2000, width = 2000, unit = 'px')

annoGene <- c("Ovol2","Abhd12b","Thbs4","Ptpn14","Hcrt","Adora2a")

tiff(filename = paste("./Fig_section2/htmp.marker.tiff", sep = ""), res = 300, height = 1000, width = 1000)
AverageHeatmap(object = merge.obj,
               assays = "Spatial",
               markerGene = top_10markers$gene,
               annoCol = TRUE,
               myanCol = c("#F8766D","#B79F00","#00BA38","#00BFC4","#619CFF","#F564E3"),
               showRowNames = F,
               markGenes = annoGene)
dev.off()

# DoHeatmap(merge.obj, group.by = "anatomy",features = unique(top_10markers$gene))+
#   scale_fill_gradientn(colors = c("blue", "white", "red"))+ NoLegend()
# ggsave(paste("./Fig_section2/Dohtmp.100dpi.region.marker.tiff", sep = ""), device='tiff',dpi = 100,height = 1500, width = 1000, unit = 'px')
```

```{r}
VlnPlot(merge.obj, group.by = "anatomy",
        features = c("Ovol2","Abhd12b","Thbs4","Ptpn14","Hcrt","Adora2a"),
        stack = T, flip = T)+ NoLegend()
ggsave(paste("./Fig_section2/Vlnplot.region.marker.tiff", sep = ""), device='tiff', dpi=100, height = 1000, width = 1000, unit = 'px')
```

# DEG

1.  DEG table + Avg expression
2.  Barplot of DEG
3.  Transformed Volcano plot
4.  GO
5.  Subclustering of Hippocampus & Amygdala

```{r assign condition}
merge.obj$condition <- 0
merge.obj$condition[grepl("d0_cc_1h", merge.obj$orig.ident)] <- "d0_cc_1h"
merge.obj$condition[grepl("d0_cfc_1h", merge.obj$orig.ident)] <- "d0_cfc_1h"

merge.obj$condition[grepl("d0_cc_4h", merge.obj$orig.ident)] <- "d0_cc_4h"
merge.obj$condition[grepl("d0_cfc_4h", merge.obj$orig.ident)] <- "d0_cfc_4h"

merge.obj$condition[grepl("d1_cc_4h", merge.obj$orig.ident)] <- "d1_cc_4h"
merge.obj$condition[grepl("d1_cfc_4h", merge.obj$orig.ident)] <- "d1_cfc_4h"

merge.obj$condition[grepl("home_cage_", merge.obj$orig.ident)] <- "home_cage"

merge.obj$condition <- factor(merge.obj$condition, levels = c("home_cage","d0_cc_1h","d0_cfc_1h","d0_cc_4h","d0_cfc_4h","d1_cc_4h","d1_cfc_4h"))
```

```{r assign anatomy}

table(merge.obj$orig.ident,merge.obj$condition)

# write.csv(table(merge.obj$orig.ident,merge.obj$condition), file = "./Fig_section2/sample_condition.table.csv")
# write.csv(table(merge.obj$orig.ident,merge.obj$anatomy), file = "./Fig_section2/sample_anatomy.table.csv")
```




```{r cfc vs cc in each region}
unique(merge.obj$anatomy)

Idents(merge.obj) <- "anatomy"

merge.obj$combined_condition <- paste(merge.obj$anatomy,merge.obj$condition,sep = "_")


up_count <- c()
down_count <- c()

time <- c("d0_1h","d0_4h","d1_4h")

for (ct in unique(merge.obj$anatomy)) {
  ct.name <- ct
  
  if (ct == "Cortex"){
    ct.name <- "Cortex"
  }
  if (ct == "Cerebral Nuclei"){
    ct.name <- "Cerebral.Nuclei"
  }
  
  for (i in 1:3){
      marker <- FindMarkers(merge.obj, 
                     ident.1 = unique(merge.obj$condition)[2*i], ident.2 = unique(merge.obj$condition)[2*i-1], # cfc cc
                     # ident.1 = unique(merge.obj$condition)[2*i], ident.2 = "home_cage", # cfc vs home cage
                     # ident.1 = unique(merge.obj$condition)[2*i-1], ident.2 = "home_cage", # cc vs home cage
                     group.by = 'condition',
                     subset.ident = ct,
                     pseudocount.use = 0.001)
      # add average expression to DEG table
      avg <- as.data.frame(AverageExpression(merge.obj,assays = "Spatial",
                              features = rownames(marker),group.by = "combined_condition"))
      marker$cfc_avg <- avg[,paste("Spatial.",ct.name,"_",unique(merge.obj$condition)[2*i],sep = "")]
      marker$cc_avg <- avg[,paste("Spatial.",ct.name,"_",unique(merge.obj$condition)[2*i-1],sep = "")]
      marker$homecage_avg <- avg[,paste("Spatial.",ct.name,"_home_cage",sep = "")]
      
      marker$celltype <- ct.name
      marker$time <- time[i]
      
      marker$gene <- rownames(marker)
      marker$regulation <- ifelse(marker$avg_log2FC > 0,paste0("Up"),paste0("Down"))
      
      marker$sig <- ""
      marker$sig[abs(marker$avg_log2FC) > log2(1.2) & marker$p_val_adj < 0.05] <- paste(ct.name,"sig",sep = "_")
      marker$sig[marker$sig == ""] <- "not_sig"
      marker$sig <- factor(marker$sig, levels = c("not_sig",paste(ct.name,"sig",sep = "_")))
    
      
      # Output the DEG
      assign(paste(ct.name,time[i],"cfcvscc.marker", sep = "."), marker)
      # write.csv(marker,file = paste(ct.name,time[i],"cfcvscc.marker.csv", sep = "."))
      
      # assign(paste(ct.name,time[i],"cfcvshomecage.marker", sep = "."), marker)
      # write.csv(marker,file = paste(ct.name,time[i],"cfcvshomecage.marker.csv", sep = "."))
      
      # assign(paste(ct.name,time[i],"ccvshomecage.marker", sep = "."), marker)
      # write.csv(marker,file = paste(ct.name,time[i],"ccvshomecage.marker.csv", sep = "."))
      
      up_count <- c(up_count, sum(marker$avg_log2FC >= log2(1.2) & marker$p_val_adj <= 0.05))
      down_count <- c(down_count, sum(marker$avg_log2FC <= -log2(1.2) & marker$p_val_adj <= 0.05))
      }
}
```

```{r barplot}
plot.list=list()
for (i in 1:3){
  bar_data <- data.frame(celltype = rep(unique(merge.obj$anatomy),2),
                       number = c(up_count[(i*6-5):(i*6)],-down_count[(i*6-5):(i*6)]),
                       direct = c(rep("up",6),rep("down",6)))
  
  bar.plot <- ggplot(bar_data, aes(x = celltype, y = number, fill = direct)) +
  geom_bar(stat = "identity", position = "identity") +
  labs(x = "Cluster", y = "Number of DEGs", fill = "Direction") +
  geom_text(aes(label=abs(number)), position=position_dodge(width=0), 
            hjust= ifelse(bar_data$direct == 'up', 0.5, 0.5), size=5) +
  scale_fill_manual(values = c("up" = "red", "down" = "blue"))+
  theme(
    axis.text=element_text(size=10),
    # axis.text.x = element_blank(), # Rotate x-axis labels
    panel.background = element_rect(fill = "white"), # Change background to white
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    panel.border = element_rect(size = 2,fill = NA)
  )
  plot.list[[i]] <- bar.plot
}


wrap_plots(plot.list,ncol = 1)&theme(plot.margin = unit(c(0,0,0,0),"cm"))

# ggsave(paste("./Barplot.cfcvscc.tiff", sep = ""), device='tiff', dpi=500, height = 10, width = 8, unit = 'in')
# ggsave(paste("./Barplot.cfcvshomecage.tiff", sep = ""), device='tiff', dpi=500, height = 10, width = 8, unit = 'in')
# ggsave(paste("./Barplot.ccvshomecage.tiff", sep = ""), device='tiff', dpi=500, height = 10, width = 8, unit = 'in')
```

```{r transformed volcano plot}
cfcvscc.vars <- ls(envir = .GlobalEnv, pattern = "cfcvscc.marker")

# Get the actual variables from the names
matching_data_frames <- sapply(cfcvscc.vars, get, envir = .GlobalEnv, simplify = FALSE)

# Use do.call to rbind all the data frames together
combined_data_frame <- do.call(rbind, matching_data_frames)

```


```{r}
combined_data_frame <- combined_data_frame%>%arrange(celltype,sig)

combined_data_frame$padj_log10_neg <-  -log10(combined_data_frame$p_val_adj)
combined_data_frame$padj_log10_neg <- ifelse(combined_data_frame$avg_log2FC > 0,
                                        combined_data_frame$padj_log10_neg,
                                        -combined_data_frame$padj_log10_neg)
```



```{r}
color_ct <- c("#F8766D","#B79F00","#00BA38","#00BFC4","#619CFF","#F564E3")
names(color_ct) <- c("Cortex_sig","Thalamus_sig","Hippocampus_sig","OLF_sig","Hypothalamus_sig","Cerebral.Nuclei_sig")


plot.list=list()

# intermediate.df <- combined_data_frame[combined_data_frame$time== "d0_1h",]
# intermediate.df <- combined_data_frame[combined_data_frame$time== "d0_4h",]
intermediate.df <- combined_data_frame[combined_data_frame$time== "d1_4h",]

for (ci in c("Cortex","Thalamus","Hippocampus","OLF","Hypothalamus","Cerebral.Nuclei")) {
  print(ci)
  tmpdf=intermediate.df %>% filter(celltype == ci)
  minabs=abs(min(tmpdf$padj_log10_neg))
  maxabs=max(tmpdf$padj_log10_neg)
  thre=0
  if(minabs < maxabs) {
    tmpdf$padj_log10_neg[tmpdf$padj_log10_neg > minabs] = minabs
    thre=minabs
  }
  if(minabs > maxabs) {
    tmpdf$padj_log10_neg[tmpdf$padj_log10_neg < (-maxabs)] = -maxabs
    thre=maxabs
  }
  if(minabs == maxabs & maxabs == Inf) {
    thre = min(
      abs(
        range(
          tmpdf$padj_log10_neg[tmpdf$padj_log10_neg < Inf & tmpdf$padj_log10_neg > -Inf]
        )
      )
    )
    tmpdf$padj_log10_neg[tmpdf$padj_log10_neg < (-thre)] = -thre
    tmpdf$padj_log10_neg[tmpdf$padj_log10_neg > thre] = thre
  }
  
  plotdata = tmpdf
  tmpdf=tmpdf%>%filter(sig != "not") #这里我取了logFC最极端的几个gene来标注文本，实际处理中不一定这样做
  tmpdf=tmpdf%>%arrange(desc(avg_log2FC))
  tmpdf.a=head(tmpdf%>%filter(avg_log2FC > 0),5)
  tmpdf.a$d=thre*2*0.05+(-thre)-tmpdf.a$padj_log10_neg
  tmpdf.b=tail(tmpdf%>%filter(avg_log2FC < 0),5)
  tmpdf.b$d=thre*2*0.95-thre  - tmpdf.b$padj_log10_neg
  textdata.down = tmpdf.b
  textdata.up   = tmpdf.a
  
  ###画图
  tmpplot <- plotdata%>%ggplot(aes(x=padj_log10_neg,y=avg_log2FC))+
    geom_point(aes(color=sig),size=3)+
    geom_hline(yintercept = c(-log2(1.2),log2(1.2)),linetype="dashed")+
    geom_hline(yintercept = c(0),linetype="solid")+
    labs(title = ci)+
    scale_color_manual(values = c(color_ct,"not_sig"="#dee1e6"))+
    scale_y_continuous("log2(Fold Change)",expand = c(0.02,0),limits = c(-3,3))+
    theme_bw()+
    theme(
      panel.grid = element_blank(),
      legend.position = "none",
      
      axis.ticks.x.bottom = element_blank(),
      axis.text.x.bottom = element_blank(),
      axis.title.x.bottom = element_blank(),
      axis.text.y.left = element_text(size = 14,color = "black"),
      axis.title.y.left = element_text(size = 16),
      
      plot.title = element_text(size = 16,hjust = 0.5)
    )
  
  index <- which(ci == c("Cortex","Thalamus","Hippocampus","OLF","Hypothalamus","Cerebral.Nuclei"))
  if (index!=1) {
    tmpplot <- tmpplot+theme(
      axis.title.y.left = element_blank(),
      axis.ticks.y.left = element_blank(),
      axis.text.y.left = element_blank()
    )
  }
  plot.list[[get("index")]] <- tmpplot
} 

wrap_plots(plot.list,ncol = 6)&theme(plot.margin = unit(c(0,0,0,0),"cm")) # 400*500  800*500
# ggsave(paste("./Fig_section3/TransformedVolcano.cfcvscc.d0_1h.tiff", sep = ""), device='tiff', dpi=100, height = 1000, width = 1000, unit = 'px')
# ggsave(paste("./Fig_section3/TransformedVolcano.cfcvscc.d0_4h.tiff", sep = ""), device='tiff', dpi=100, height = 1000, width = 1000, unit = 'px')
# ggsave(paste("./Fig_section3/TransformedVolcano.cfcvscc.d1_4h.tiff", sep = ""), device='tiff', dpi=100, height = 1000, width = 1000, unit = 'px')
```

"Cortex","Thalamus","Hippocampus","OLF","Hypothalamus","Cerebral.Nuclei"
"d0_1h" "d0_4h" "d1_4h"
```{r}
library(ComplexUpset)
library(ComplexHeatmap)
```



```{r Upset plot}
intermediate.df <- combined_data_frame[combined_data_frame$time== "d0_1h",]

lt <- list(Cortex = intermediate.df[intermediate.df$celltype == "Cortex" & intermediate.df$sig != "not_sig",]$gene,
          Thalamus = intermediate.df[intermediate.df$celltype == "Thalamus" & intermediate.df$sig != "not_sig",]$gene,
          Hippocampus = intermediate.df[intermediate.df$celltype == "Hippocampus" & intermediate.df$sig != "not_sig",]$gene,
          OLF = intermediate.df[intermediate.df$celltype == "OLF" & intermediate.df$sig != "not_sig",]$gene,
          Hypothalamus = intermediate.df[intermediate.df$celltype == "Hypothalamus" & intermediate.df$sig != "not_sig",]$gene,
          Cerebral.Nuclei = intermediate.df[intermediate.df$celltype == "Cerebral.Nuclei" & intermediate.df$sig != "not_sig",]$gene)


m <- make_comb_mat(lt)


tiff("./Fig_section3/Upsetplot.d0_1h.tiff", width = 1600, height = 1000,res = 200)

ComplexHeatmap::UpSet(
  m,
  comb_order = order(comb_size(m),decreasing = T),
  set_order = c("Cortex","Thalamus","Hippocampus","OLF","Hypothalamus","Cerebral.Nuclei"),
  top_annotation = upset_top_annotation(m, add_numbers = TRUE),
  right_annotation = upset_right_annotation(
    m,
    add_numbers = TRUE,
    annotation_name_side = "top",
    axis_param = list(side = "top")
  ))


# Close the device
dev.off()
```


```{r heatmap instead of transvolcano}
combined_data_frame.sig <- combined_data_frame[combined_data_frame$sig != "not_sig",]

write.csv(combined_data_frame.sig, file = "./Fig_section3/brain.region.sig.csv")


# Sort by time and celltype
sorted_data_frame <- combined_data_frame.sig %>%
  arrange(time, celltype)

# Create a new column combining celltype and time for sorting
sorted_data_frame$sample_condition <- paste(sorted_data_frame$celltype, sorted_data_frame$time, sep = "_")

target.gene <- sorted_data_frame$gene[!duplicated(sorted_data_frame$gene) & sorted_data_frame$celltype == "Cortex"]


combined_condition.level <- c()
for (i in levels(merge.obj$anatomy)) {
  for(j in levels(merge.obj$condition)) {
    combined_condition.level <- c(combined_condition.level, paste(i,j,sep = "_"))
  }
}


merge.obj$combined_condition <- factor(merge.obj$combined_condition, 
                                       levels =combined_condition.level)



Idents(merge.obj) <- "combined_condition"

AverageHeatmap(object = subset(merge.obj, subset = anatomy == "Cortex"),
               assays = "Spatial",group.by = "combined_condition",
               markerGene = target.gene,
               # annoCol = TRUE,
               # myanCol = c("#F8766D","#B79F00","#00BA38","#00BFC4","#619CFF","#F564E3"),
               cluster_rows = T,
               showRowNames = F)


```




```{r comparecluster for GO}

plot.list <- list()
for (timepoint in time) {
  intermediate.df <- combined_data_frame[combined_data_frame$time== timepoint,]

  lt <- list(Cortex = intermediate.df[intermediate.df$celltype == "Cortex" & intermediate.df$sig != "not_sig",]$gene,
            Thalamus = intermediate.df[intermediate.df$celltype == "Thalamus" & intermediate.df$sig != "not_sig",]$gene,
            Hippocampus = intermediate.df[intermediate.df$celltype == "Hippocampus" & intermediate.df$sig != "not_sig",]$gene,
            OLF = intermediate.df[intermediate.df$celltype == "OLF" & intermediate.df$sig != "not_sig",]$gene,
            Hypothalamus = intermediate.df[intermediate.df$celltype == "Hypothalamus" & intermediate.df$sig != "not_sig",]$gene,
            Cerebral.Nuclei = intermediate.df[intermediate.df$celltype == "Cerebral.Nuclei" & intermediate.df$sig != "not_sig",]$gene)
  
  convert_to_entrez <- function(gene_vector, orgdb) {
    tryCatch({
      bitr(gene_vector, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = orgdb)
    }, error = function(e) {
      message("Error: ", e$message)
      return(data.frame(SYMBOL = gene_vector, ENTREZID = NA))  # Return NA if not found
    })
  }
  
  # Apply the function to each element in the list
  lt_entrez <- lapply(lt, convert_to_entrez, orgdb = org.Mm.eg.db)
  
  lt_entrez.update <- list(Cortex = lt_entrez$Cortex$ENTREZID,
                           Thalamus = lt_entrez$Thalamus$ENTREZID,
                           Hippocampus = lt_entrez$Hippocampus$ENTREZID,
                           OLF = lt_entrez$OLF$ENTREZID,
                           Hypothalamus = lt_entrez$Hypothalamus$ENTREZID,
                           Cerebral.Nuclei = lt_entrez$Cerebral.Nuclei$ENTREZID)
  
  
  ego <- compareCluster(lt_entrez.update,
                        keyType = "ENTREZID",
                        ont = "BP",
                        OrgDb='org.Mm.eg.db',
                        readable = T)
  
  p <- dotplot(ego,size = "Count", showCategory = 3)
  
  index <- which(timepoint == time)
  if (index!=1) {
    tmpplot <- tmpplot+theme(
      axis.title.y.left = element_blank(),
      axis.ticks.y.left = element_blank(),
      axis.text.y.left = element_blank()
    )
  }
  plot.list[[get("index")]] <- p
}



```




```{r}
wrap_plots(plot.list,ncol = 1)&theme(plot.margin = unit(c(0,0,0,0),"cm"))

ggsave(paste("./Fig_section3/GO.compare.2.5vs1.tiff", sep = ""), device='tiff', dpi=100, height = 2500, width = 1000, unit = 'px')
```






```{r}


for (ct in unique(merge.obj$anatomy)) {
  ct.name <- ct
  
  if (ct == "Frontal Cortex"){
    ct.name <- "Frontal.Cortex"
  }
  if (ct == "Cerebral Nuclei"){
    ct.name <- "Cerebral.Nuclei"
  }
  
 for (i in 1:3){
      marker <- FindMarkers(merge.obj, 
                     # ident.1 = unique(merge.obj$condition)[2*i], ident.2 = unique(merge.obj$condition)[2*i-1],
                     ident.1 = unique(merge.obj$condition)[2*i], ident.2 = "home_cage", # cfc vs home cage
                     # ident.1 = unique(merge.obj$condition)[2*i-1], ident.2 = "home_cage", # cc vs home cage
                     group.by = 'condition',
                     subset.ident = ct,
                     pseudocount.use = 0.001)
      marker <- marker[marker$p_val_adj < 0.05 & abs(marker$avg_log2FC) > log2(1.2),]
      
  
      assign("eg", bitr(rownames(marker), fromType="SYMBOL", toType="ENTREZID",OrgDb="org.Mm.eg.db"))
  
      ego <- enrichGO(gene = eg$ENTREZID,
                      OrgDb = org.Mm.eg.db,
                      ont = "BP",
                      pAdjustMethod = "BH",
                      pvalueCutoff  = 0.05,
                      qvalueCutoff = 0.05,
                      readable = TRUE)
      if (nrow(ego@result[ego@result$p.adjust < 0.05 & ego@result$qvalue < 0.05,]) <= 0){
        next
      }
      ego <- pairwise_termsim(ego)
      ego <- simplify(ego)
      
      
      # write.csv(ego@result, file = paste(ct.name,time[i],"cfcvscc.GO.csv", sep = "."))
      write.csv(ego@result, file = paste(ct.name,time[i],"cfcvshomecage.GO.csv", sep = "."))
      # write.csv(ego@result, file = paste(ct.name,time[i],"ccvshomecage.GO.csv", sep = "."))

      # go_analysis <- ego@result[ego@result$p.adjust < 0.05 & ego@result$qvalue < 0.05,]
      # 
      # simMatrix <- calculateSimMatrix(go_analysis$ID,
      #                                 orgdb="org.Mm.eg.db",
      #                                 ont="BP",
      #                                 method="Rel")
      # 
      # scores <- setNames(-log10(go_analysis$qvalue), go_analysis$ID)
      # reducedTerms <- reduceSimMatrix(simMatrix,
      #                                 scores,
      #                                 threshold=0.7,
      #                                 orgdb="org.Mm.eg.db")
      # treemapPlot(reducedTerms)
      # 
      # ggsave(paste(ct.name,time[i],"cfcvscc.GO.tiff", sep = "."), 
      #        device='tiff', dpi=500, height = 10, width = 10, unit = 'in')
      # ggsave(paste(ct.name,time[i],"cfcvshomecage.GO.tiff", sep = "."), 
      #        device='tiff', dpi=500, height = 10, width = 10, unit = 'in')
      # ggsave(paste(ct.name,time[i],"ccvshomecage.GO.csv", sep = "."), 
      #        device='tiff', dpi=500, height = 10, width = 10, unit = 'in')
      }
}


```



```{r}
library(biomaRt)
```

GO:0007611 learning or memory
GO:0007614 short-term memory

```{r}
fear_condition_genes <- mapIds(org.Mm.eg.db,
      keys = "GO:0042596",
      keytype="GO",
      column="SYMBOL", multiVals = "list")

fear_condition_genes <- fear_condition_genes$`GO:0042596`


learning_genes <- mapIds(org.Mm.eg.db,
      keys = "GO:0007611",
      keytype="GO",
      column="SYMBOL", multiVals = "list")

learning_genes <- learning_genes$`GO:0007611`


short_term_memory_genes <- mapIds(org.Mm.eg.db,
      keys = "GO:0007614",
      keytype="GO",
      column="SYMBOL", multiVals = "list")

short_term_memory_genes <- short_term_memory_genes$`GO:0007614`

IEG.gene <- c("Bdnf", "Homer1", "Fos","Arc","Btg2","Fosl2","Npas4","Nr4a1")
```


```{r}
library(AUCell)
```


```{r}

cells_rankings <- AUCell_buildRankings(merge.obj@assays$Spatial@data,splitByBlocks=TRUE)

cells_AUC.fear_condition_genes <- AUCell_calcAUC(fear_condition_genes, cells_rankings, 
                            aucMaxRank=nrow(cells_rankings)*0.1)

cells_AUC.learning_genes <- AUCell_calcAUC(learning_genes, cells_rankings, 
                            aucMaxRank=nrow(cells_rankings)*0.1)

cells_AUC.short_term_memory_genes <- AUCell_calcAUC(short_term_memory_genes, cells_rankings, 
                            aucMaxRank=nrow(cells_rankings)*0.1)


cells_AUC.IEG <- AUCell_calcAUC(IEG.gene, cells_rankings, 
                            aucMaxRank=nrow(cells_rankings)*0.1)


```


```{r}
merge.obj$fear_condition_auc <- as.numeric(getAUC(cells_AUC.fear_condition_genes))
merge.obj$learning_auc <- as.numeric(getAUC(cells_AUC.learning_genes))
merge.obj$short_term_memory_auc <- as.numeric(getAUC(cells_AUC.short_term_memory_genes))

merge.obj$IEG_auc <- as.numeric(getAUC(cells_AUC.short_term_memory_genes))
```






```{r}
VlnPlot(merge.obj, features = c("fear_condition_auc"),
        group.by = "anatomy",
        split.by = "condition",
        pt.size = 0)

VlnPlot(merge.obj, features = c("learning_auc"),
        group.by = "anatomy",
        split.by = "condition",
        pt.size = 0)

VlnPlot(merge.obj, features = c("short_term_memory_auc"),
        group.by = "anatomy",
        split.by = "condition",
        pt.size = 0)

VlnPlot(merge.obj, features = c("IEG_auc"),
        group.by = "anatomy",
        split.by = "condition",
        pt.size = 0)
```


```{r}
SpatialFeaturePlot(merge.obj, features = "fear_condition_auc",
               pt.size.factor = 1.6,
               ncol = 4)

ggsave(paste("./Fig_section3/Spfeatureplot.fear_condition_auc.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialFeaturePlot(merge.obj, features = "short_term_memory_auc",
               pt.size.factor = 1.6,
               ncol = 4)

ggsave(paste("./Fig_section3/Spfeatureplot.short_term_memory_auc.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialFeaturePlot(merge.obj, features = "learning_auc",
               pt.size.factor = 1.6,
               ncol = 4)

ggsave(paste("./Fig_section3/Spfeatureplot.learning_auc.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialFeaturePlot(merge.obj, features = "IEG_auc",
               pt.size.factor = 1.6,
               ncol = 4)

ggsave(paste("./Fig_section3/Spfeatureplot.IEG_auc.tiff", sep = ""), device='tiff', dpi=200, height = 13, width = 18, unit = 'in')
```


```{r}
temp.df <- data.frame(
  fear_condition_auc = merge.obj$fear_condition_auc,
  anatomy = merge.obj$anatomy,
  condition = merge.obj$condition
)

# Creating the density plot
ggplot(temp.df, aes(x = fear_condition_auc, fill = condition)) +
  geom_density(alpha = 0.5) +  # Adjust the transparency with the alpha argument
  facet_wrap(~anatomy) +  # Faceting by 'condition'
  theme_bw() +
  theme(legend.position = "right") 

ggsave(paste("./Fig_section3/density.fear_condition_auc.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')

```


```{r}
library(UCell)
```


```{r}
func.signacture <- list()
func.signacture$fear_condition_genes <- fear_condition_genes
func.signacture$learning_genes <- learning_genes
func.signacture$short_term_memory_genes <- short_term_memory_genes
```


```{r}
merge.obj <- AddModuleScore_UCell(merge.obj, features = func.signacture)

merge.obj$short_term_memory_genes_UCell
```

```{r}
SpatialFeaturePlot(merge.obj, features = "fear_condition_genes_UCell",
               pt.size.factor = 1.6,
               ncol = 4)

ggsave(paste("./Fig_section3/Spfeatureplot.fear_condition_genes_UCell.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')

SpatialFeaturePlot(merge.obj, features = "learning_genes_UCell",
               pt.size.factor = 1.6,
               ncol = 4)
ggsave(paste("./Fig_section3/Spfeatureplot.short_term_memory_genes_UCell.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialFeaturePlot(merge.obj, features = "short_term_memory_genes_UCell",
               pt.size.factor = 1.6,
               ncol = 4)
ggsave(paste("./Fig_section3/Spfeatureplot.learning_genes_UCell.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')

```


```{r}
merge.obj <- AddModuleScore(merge.obj, features = func.signacture)

merge.obj$Cluster1
```



```{r}
SpatialFeaturePlot(merge.obj, features = "Cluster1",
               pt.size.factor = 1.6,
               ncol = 4)
ggsave(paste("./Fig_section3/Spfeatureplot.fear_condition_module.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialFeaturePlot(merge.obj, features = "Cluster2",
               pt.size.factor = 1.6,
               ncol = 4)
ggsave(paste("./Fig_section3/Spfeatureplot.learning_module.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')


SpatialFeaturePlot(merge.obj, features = "Cluster3",
               pt.size.factor = 1.6,
               ncol = 4)
ggsave(paste("./Fig_section3/Spfeatureplot.short_term_memory_module.tiff", sep = ""), device='tiff', dpi=500, height = 13, width = 18, unit = 'in')
```



```{r}
save(merge.obj, file = "./Data/merge.obj.RData")
```

